---
- set_fact:
    package_manager: apt
  when: ansible_os_family == "Debian"

- set_fact:
    package_manager: yum
  when: ansible_os_family == "RedHat"

- name: Including distro specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}_{{ ansible_distribution_major_version }}.yml"
    - "{{ package_manager }}_systems.yml"
    - empty.yml

- name: Install container packages
  package:
    name: "{{ container_packages }}"
    state: latest
  when: container_packages|length > 0

- set_fact:
    container_service_conf: "/etc/containers/registries.conf"
  when:
    - "'podman' in container_packages"
  tags:
    - container-mirror

- set_fact:
    container_service_conf: "/etc/docker/daemon.json"
  when:
    - "'docker.io' in container_packages"
    - "'podman' not in container_packages"
  tags:
    - container-mirror

- import_tasks: container_mirror.yml
  when:
    - container_mirror is defined
    - container_mirror_cert is defined
  tags:
    - container-mirror

# I hate this but there was no other elegant way to do it.  I considered:
# 1) Copying {{ packages }} from roles/testnode/vars/redhat_8.yml to
#    ceph-octo-secrets with podman-docker removed but I really don't want to
#    keep two separate RHEL8 package lists based on the lab we're in.
# 2) Removing during the tools/prep-fog-capture playbook but QE runs
#    ceph-cm-ansible again sometimes which would reinstall podman-docker.
- import_tasks: downstream.yml
  when: lab_name is defined and lab_name == "octo"
