---
# These defaults are present to allow certain tasks to no-op if a secrets repo
# hasn't been defined. If you want to override these, do so in the secrets repo
# itself. We override these in  $repo/ansible/inventory/group_vars/cobbler.yml
secrets_repo:
  name: UNDEFINED
  url: null

# Where to download ISOs
iso_dir: /var/lib/cobbler/isos
# Mount point to use for ISOs during import
iso_mount: /mnt/iso
# Where to put kernel/initrd files for image-based ISOs
other_image_dir: /var/lib/cobbler/other_boot_images

users_digest_lines:
 # default password is 'cobbler' - change it in a secrets repo!
 - "cobbler:Cobbler:a2d6bae81669d707b72c0bd9806e01f3"

settings:
  - name: yum_post_install_mirror
    value: 0
  - name: signature_url
    value: http://cobbler.github.io/signatures/2.6.x/latest.json
  - name: server
    value: "{{ ip }}"
  - name: next_server
    value: "{{ ip }}"
  - name: pxe_just_once
    value: 1

kickstarts:
  - cephlab_rhel.ks
  - cephlab_rhel_sdc.ks
  - cephlab_ubuntu.preseed
  - cephlab_opensuse_leap.xml
  
snippets:
  - cephlab_user
  - cephlab_hostname
  - cephlab_packages_rhel
  - cephlab_rc_local
  - cephlab_rhel_disks
  - cephlab_post_install_kernel_options
  - cephlab_rhel_rhsm

scripts:
  - cephlab_preseed_late

triggers:
  - install/post/cephlab_ansible.sh

utils:
  - console.sh
  - reboot.sh
  - reimage.sh

cm_user_ssh_keys: []

cm_user: ''
cm_user_uid: ''

# A list of lines to add to resolv.conf and resolv.conf.d/base
# An example:
#   resolvconf:
#      - "nameserver x.x.x.x"
#      - "search an.example.com"
resolvconf: []

power_type: ipmilan
# power_user and power_pass defaults will need to be overridden in a secrets
# repo to be useful
power_user: poweruser
power_pass: powerpass

pip_packages:
  - pip
  - ansible

cobbler_settings_file: /etc/cobbler/settings

kopts_flag: "--kopts"

autoinstall_flag: "--kickstart"

ks_dir: /var/lib/cobbler/kickstarts
