---
- name: Disable default nginx config
  file:
    name: /etc/nginx/sites-enabled/default
    state: absent

- name: Ship nginx config
  template:
    src: nginx.conf
    dest: "{{ nginx_available }}/test_logs.conf"

- name: Enable nginx config
  file:
    src: "{{ nginx_available }}/test_logs.conf"
    dest: "{{ nginx_enabled }}/test_logs.conf"
    state: link

# Ignore errors in case service doesn't exist
- name: Disable apache httpd
  service:
    name: "{{ apache_service }}"
    enabled: no
    state: stopped
  ignore_errors: true

- name: Enable nginx
  service:
    name: nginx
    enabled: yes
    state: reloaded
  changed_when: false
