---
- name: Checkout the repo
  git:
    repo: "{{ pulpito_repo }}"
    dest: "{{ pulpito_repo_path }}"
  become_user: "{{ pulpito_user }}"
  tags:
    - repos

- name: Look for the virtualenv
  stat: 
    path: "{{ pulpito_repo_path }}/virtualenv"
    get_checksum: no
    get_md5: no
  register: virtualenv

- name: Create the virtualenv
  shell: virtualenv ./virtualenv chdir={{ pulpito_repo_path }}
  become_user: "{{ pulpito_user }}"
  when: virtualenv.stat.exists == false

- name: Self-upgrade pip
  pip:
    name: "pip"
    state: "latest"
    chdir: "{{ pulpito_repo_path }}"
    virtualenv: "{{ pulpito_repo_path }}/virtualenv"
  become_user: "{{ pulpito_user }}"

- name: Install requirements via pip
  pip:
    chdir: "{{ pulpito_repo_path }}"
    requirements: "./requirements.txt"
    virtualenv: "{{ pulpito_repo_path }}/virtualenv"
  #no_log: true
  become_user: "{{ pulpito_user }}"

- name: Check for pulpito config
  stat:
    path: "{{ pulpito_repo_path }}/prod.py"
    get_checksum: no
    get_md5: no
  register: pulpito_config

- name: Copy pulpito config
  shell: cp ./config.py.in prod.py chdir={{ pulpito_repo_path }}
  when: pulpito_config.stat.exists == false
  become_user: "{{ pulpito_user }}"

- name: Set paddles_address
  lineinfile:
    dest: "{{ pulpito_repo_path }}/prod.py"
    regexp: "^paddles_address = "
    line: "paddles_address = '{{ paddles_address|mandatory }}'"
  register: pulpito_config

