#!/bin/bash

#
# {{ ansible_managed }}
#

# In order to allow Puddle to communicate with Red Hat's Errata Tool, we need
# active Kerberos credentials. This script wraps /usr/bin/puddle with the
# k5start utility.

set -e

exec k5start -U -f {{ puddle.kerberos_keytab }} -- puddle "$@"
