---
- name: Create group
  group:
    name: "{{ paddles_user }}"
    state: present
  tags:
    - user
- name: Create user
  user:
    name: "{{ paddles_user }}"
    state: present
    shell: /bin/bash
  tags:
    - user
