---
- name: Install ntp package on rpm based systems.
  yum:
    name: ntp
    state: present
  when: ansible_pkg_mgr  == "yum"
  tags:
    - packages

- name: Install ntp package on apt based systems.
  apt:
    name: ntp
    state: present
  when: ansible_pkg_mgr  == "apt"
  tags:
    - packages

# See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=806556.
# ifdown/ifup would often leave ntpd not running on xenial.
# We do our own ntpdate dance in teuthology's clock task.
- name: Remove racy /etc/network/if-up.d/ntpdate on xenial
  file:
    name: /etc/network/if-up.d/ntpdate
    state: absent
  when: ansible_distribution == "Ubuntu" and
        ansible_distribution_major_version == '16'

- name: Create the ntp.conf file.
  template:
    src: ntp.conf
    dest: /etc/ntp.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart ntp

- name: Make sure ntpd is running.
  service:
    name: "{{ntp_service_name}}"
    enabled: yes
    state: started
