---
- name: Install ntp package on rpm based systems.
  yum:
    name: ntp
    state: present
  when: ansible_pkg_mgr  == "yum"
  tags:
    - packages

- name: Install ntp package on apt based systems.
  apt:
    name: ntp
    state: present
  when: ansible_pkg_mgr  == "apt"
  tags:
    - packages

- name: Create the ntp.conf file.
  template:
    src: ntp.conf
    dest: /etc/ntp.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart ntp

- name: Make sure ntpd is running.
  service:
    name: "{{ntp_service_name}}"
    enabled: yes
    state: started
