---
# Creating reverse records requires ansible_version.major >=2
# to use the skip_missing flag of with_subelements
# https://github.com/ansible/ansible/issues/9827
- name: Bail if local ansible version is older than v2.0
  assert:
    that: "{{ ansible_version.major }} >= 2"

- name: Create zone file path
  file:
    path: "{{ named_conf_zones_path }}"
    state: directory

- name: Set named_serial variable
  set_fact:
    named_serial: "{{ ansible_date_time.epoch }}"

- name: Create forward zone files for dynamic domains
  template:
    src: forward.j2
    dest: "{{ named_conf_zones_path }}/{{ item.key }}"
    validate: named-checkzone {{ item.key }} %s
    # Only write if zone file doesn't already exist
    # This makes sure we don't clobber DDNS records
    force: no
  with_dict: "{{ named_domains }}"
  notify: reload named
  when: item.value.dynamic == true

- name: Write forward zone files
  template:
    src: forward.j2
    dest: "{{ named_conf_zones_path }}/{{ item.key }}"
    validate: named-checkzone {{ item.key }} %s
  with_dict: "{{ named_domains }}"
  notify: reload named
  when: item.value.dynamic != true

- name: Write reverse zone files
  template:
    src: reverse.j2
    dest: "{{ named_conf_zones_path }}/{{ item.1 }}"
    validate: named-checkzone {{ item.1 }} %s
  with_subelements:
    - "{{ named_domains }}"
    - reverse
    - flags:
      skip_missing: True
  notify: reload named
