---
# Restart fail2ban
- name: restart fail2ban
  service:
    name: fail2ban
    state: restarted

# Reload fail2ban
- name: reload fail2ban
  service:
    name: fail2ban
    state: reloaded

# Restart sshd
- name: restart sshd
  service:
    name: sshd
    state: restarted

# Reload nginx, but only if the config is valid
- name: reload nginx
  shell: nginx -t && systemctl reload nginx

# Re-apply tc egress shaping
- name: restart egress shaper
  systemd:
    name: egress-shaper
    state: restarted
    daemon_reload: yes
