---
# make a lookup of all users from name to dict
- name: Build user lookup table
  set_fact:
    managed_users_by_name: >-
      {{
        dict(
          managed_users
          | map(attribute='name')
          | zip(managed_users)
        )
      }}


# fully expand extra_admin_users, which might be
# 1) a list of names only, in which case fill in fields from managed_users, or
# 2) objects with field definitions, in which case use them

- name: Initialize expanded admin list
  set_fact:
    expanded_admin_users: []

- name: Canonicalize extra_admin_users
  set_fact:
    expanded_admin_users: >-
      {{
        expanded_admin_users
        + [
            managed_users_by_name[item.name]
            if item.name in managed_users_by_name
            else item
          ]
      }}
  loop: "{{ extra_admin_users }}"
  when:
    - extra_admin_users is defined
    - extra_admin_users | length > 0

- name: Merge expanded_admin_users into managed_admin_users
  set_fact:
    managed_admin_users: >-
      {{
        (managed_admin_users | default([]))
        + expanded_admin_users
      }}
  when:
    - extra_admin_users is defined
    - extra_admin_users | length > 0

- name: Remove managed_admin_users from managed_users
  set_fact:
    managed_users: >-
      {{
        managed_users
        | rejectattr(
            'name',
            'in',
            managed_admin_users
            | map(attribute='name')
            | list
          )
        | list
      }}
  when:
    - managed_admin_users is defined
    - managed_admin_users | length > 0

# filter both by 'users' list

- name: Filter managed_users if users is set
  set_fact:
    managed_users: >-
      {{
        managed_users
        | selectattr('name', 'in', users)
        | list
      }}
  when:
    - users is defined
    - users | length > 0

- name: Filter managed_admin_users if users is set
  set_fact:
    managed_admin_users: >-
      {{
        managed_admin_users
        | selectattr('name', 'in', users)
        | list
      }}
  when:
    - users is defined
    - users | length > 0

#
# debug; enable by adding '--tags=debug' when running
#
- name: show filtered users types
  debug:
    msg:
      - "users type={{ users | type_debug }}"
      - "managed_users type={{ managed_users | type_debug }}"
      - "managed_admin_users type={{ managed_admin_users | type_debug }}"
      - "extra_admin_users type={{ extra_admin_users | type_debug }}"
  tags:
    - never

- name: show users
  debug:
    var: users
  tags:
    - never
  when:
    users is defined

- name: show managed_users
  debug:
    var: managed_users
  tags:
    - never

- name: show managed_admin_users
  debug:
    var: managed_admin_users
  tags:
    - never

- name: show extra_admin_users
  debug:
    var: extra_admin_users
  tags:
    - never
  when:
    extra_admin_users is defined
