---
- name: add ceph puddle config dir
  file:
    path: /etc/puddle/ceph
    owner: root
    group: root
    mode: 0755
    state: directory

- name: add ceph puddle config files
  template:
    src: "{{ item }}.conf"
    dest: "/etc/puddle/ceph/{{ item }}.conf"
    owner: root
    group: root
    mode: 0644
  with_items:
    - ceph-1.2-rhel-6
    - ceph-1.2-rhel-6-async
    - ceph-1.2-rhel-7
    - ceph-1.2-rhel-7-async
    - rh-common-rhel-6
    - rh-common-rhel-7
    - ceph-1.3-rhel-7
    - ceph-1.3-rhel-7-async
    - ceph-1.3.z-rhel-7

- name: add rcm-kerberos config file
  template:
    src: 'rcm-kerberos.conf'
    dest: '/etc/rcm-kerberos.conf'
    owner: root
    group: root
    mode: 0644

# Note: this file must be installed on the host independent of ansible.
- name: set permissions on keytab
  file:
    path: "{{ puddle.kerberos_keytab }}"
    owner: root
    group: puddle
    mode: 0640

- name: add faucet config file
  template:
    src: 'faucet.conf'
    dest: '/etc/puddle/faucet.conf'
    owner: root
    group: root
    mode: 0644
  notify:
   - restart faucet

- name: add ceph wrapper script for puddle
  template:
    src: 'ceph-puddle'
    dest: '/usr/local/bin/ceph-puddle'
    owner: root
    group: root
    mode: 0755

- name: add script for syncing to rcm-guest
  template:
    src: 'sync-to-rcm-guest'
    dest: '/usr/local/bin/sync-to-rcm-guest'
    owner: root
    group: root
    mode: 0755
