---
- name: Install/update packages
  yum:
    name: dhcp
    state: latest
  register: dhcp_yum_transaction
  tags: packages

- name: Check for firewalld
  command: firewall-cmd --state
  register: firewalld_state
  ignore_errors: true

- name: Check for iptables
  command: systemctl status iptables
  register: iptables_state
  ignore_errors: true

- name: Make sure firewalld is running
  service:
    name: firewalld
    state: started
    enabled: yes
  when:
    - not ansible_check_mode
    - iptables_state.rc != 0
    - not (firewalld_state.msg is defined and "'No such file or directory' in firewalld_state.msg")

- name: Configure firewalld
  firewalld:
    service: dhcp
    state: enabled
    permanent: true
    immediate: yes
  when:
    - not ansible_check_mode
    - iptables_state.rc != 0
    - not (firewalld_state.msg is defined and "'No such file or directory' in firewalld_state.msg")

- name: Write global dhcpd.conf
  template:
    src: dhcpd.conf.j2
    dest: /etc/dhcp/dhcpd.conf
    backup: yes
  register: dhcp_global_config

# NOTE: This will write the IPv6 configs too just to avoid iterating over `dhcp_subnets: {}` twice.
#       ipv6.yml will configure and restart the dhcpd6 service
- name: Write each subnet config
  template:
    src: dhcpd.subnet.conf.j2
    dest: "/etc/dhcp/dhcpd.{{ item }}.conf"
    backup: yes
  with_items: "{{ dhcp_subnets }}"
  register: dhcp_subnet_config

- name: Test new config
  command: dhcpd -t -cf /etc/dhcp/dhcpd.conf
  register: dhcpd_config_test_result
  when:
    - not ansible_check_mode
    - (dhcp_global_config is changed or dhcp_subnet_config is changed)

- name: Restart dhcpd
  service:
    name: dhcpd
    state: restarted
  when:
    - not ansible_check_mode
    - (dhcp_global_config is changed or dhcp_subnet_config is changed)
    - dhcpd_config_test_result is defined
    - dhcpd_config_test_result.rc == 0
