---
- name: Configure internal beta repos in /etc/yum.repos.d/
  template:
    src: yum_repo.j2
    dest: /etc/yum.repos.d/{{ item.key }}.repo
    owner: root
    group: root
    mode: 0644
  register: beta_repo
  with_dict: "{{ beta_repos }}"
  no_log: true

- name: Clean yum cache
  shell: yum clean all
  when: beta_repo is defined and beta_repo|changed
