---
- name: Increase the yum timeout.
  lineinfile:
    dest: /etc/yum.conf
    line: "timeout={{ yum_timeout }}"
    regexp: "^timeout="
    state: present

- name: Configure epel repos in /etc/yum.repos.d/
  template:
    src: yum_repo.j2
    dest: /etc/yum.repos.d/{{ item.key }}.repo
    owner: root
    group: root
    mode: 0644
  register: epel_repo
  with_dict: "{{ epel_repos }}"

- name: Clean yum cache
  shell: yum clean all
  when: epel_repo is defined and epel_repo is changed
