---
# this is needed for the yum-complete-transation command next
- name: Ensure yum_utils is present.
  yum:
    name: yum-utils
    state: present

- name: Removing saved yum transactions
  command: yum-complete-transaction --cleanup-only
  register: transaction_cleanup
  changed_when: "'Cleaning up' in transaction_cleanup.stdout"

- name: Ensure ceph packages are not present.
  yum:
    name: "{{ item }}"
    state: absent
  with_items: "{{ ceph_packages_to_remove }}"
  tags:
    - remove-ceph

- name: Ensure ceph dependency packages are not present.
  yum:
    name: "{{ item }}"
    state: absent
  with_items: "{{ ceph_dependency_packages_to_remove }}"
  tags:
    - remove-ceph-dependency


- name: Install packages
  yum:
    name: "{{ item }}"
    state: present 
  with_items: "{{ packages }}"
  when: packages|length > 0

- name: Install epel packages
  yum:
    name: "{{ item }}"
    state: present
    enablerepo: epel
  with_items: "{{ epel_packages }}"
  when: epel_packages|length > 0

- name: Remove packages
  yum:
    name: "{{ item }}"
    state: absent
  with_items: "{{ packages_to_remove }}"
  when: packages_to_remove|length > 0

- name: Upgrade packages
  yum:
    name: "{{ item }}"
    state: latest
  with_items: "{{ packages_to_upgrade }}"
  when: packages_to_upgrade|length > 0
