---
### This standalone playbook can be used to prep a MAAS-IMAGED testnode
### so that it can be used to capture an OS image for FOG.

- hosts:
    - testnodes
  become: true
  gather_facts: false
  tasks:

  - setup:

  - name: Remove lock files and udev rules
    file:
      path: "{{ item }}"
      state: absent
    with_items:
      - /etc/udev/rules.d/70-persistent-net.rules
      - /.cephlab_net_configured
      - /ceph-qa-ready

  - name: Get list of ifcfg scripts from host used to capture image
    shell: "ls -1 /etc/sysconfig/network-scripts/ifcfg-* | grep -v ifcfg-lo"
    register: ifcfg_scripts
    when: ansible_os_family == "RedHat"
    ignore_errors: true

  - name: Get list of ifcfg scripts from host used to capture image
    shell: "ls -1 /etc/sysconfig/network/ifcfg-* | grep -v ifcfg-lo"
    register: ifcfg_scripts
    when: ansible_os_family == "Suse"
    ignore_errors: true

  - name: Delete ifcfg scripts
    file:
      path: "{{ item }}"
      state: absent
    with_items: "{{ ifcfg_scripts.stdout_lines|default([]) }}"
    when: ifcfg_scripts is defined

  - name: Remove /var/lib/ceph mountpoint from fstab
    shell: sed -i '/\/var\/lib\/ceph/d' /etc/fstab

  - name: Unmount /var/lib/ceph
    ansible.posix.mount:
      path: /var/lib/ceph
      state: unmounted

  - name: Install one-shot service to regenerate SSH host keys on first boot
    copy:
      dest: /etc/systemd/system/regen-ssh-hostkeys.service
      owner: root
      group: root
      mode: '0644'
      content: |
        [Unit]
        Description=Regenerate SSH host keys on first boot
        ConditionPathExists=!/etc/ssh/ssh_host_ed25519_key
        Before=ssh.service

        [Service]
        Type=oneshot
        ExecStart=/usr/bin/ssh-keygen -A
        ExecStartPost=/bin/systemctl disable regen-ssh-hostkeys.service

        [Install]
        WantedBy=multi-user.target

  - name: Reload systemd daemon
    systemd:
      daemon_reload: true

  - name: Enable regen-ssh-hostkeys.service
    systemd:
      name: regen-ssh-hostkeys.service
      enabled: true

  - name: Get list of SSH host keys
    shell: "ls -1 /etc/ssh/ssh_host_*"
    register: ssh_host_keys
    ignore_errors: true

  # Key regeneration is done automatically on CentOS firstboot.
  # For Ubuntu, we'll add a systemd service to regenerate them on boot.
  - name: Delete SSH host keys so they're generated during firstboot on cloned machines
    file:
      path: "{{ item }}"
      state: absent
    with_items: "{{ ssh_host_keys.stdout_lines|default([]) }}"
    when: ssh_host_keys is defined

  - name: Unsubscribe RHEL
    command: subscription-manager unregister
    when: ansible_distribution == "RedHat"
    failed_when: false

  # A file gets leftover when a testnode is registered with Satellite that caused
  # each registered subsequent testnode to report the wrong hostname
  - name: Clean up katello facts
    file:
      path: /etc/rhsm/facts/katello.facts
      state: absent
    when: ansible_distribution == "RedHat"

  # https://bugzilla.redhat.com/show_bug.cgi?id=1814337
  - name: Disable dnf-makecache service
    service:
      name: dnf-makecache.timer
      state: stopped
      enabled: no
    when:
      - ansible_os_family == "RedHat"
      - ansible_distribution_major_version|int >= 8

  # Hopefully fixes https://github.com/ceph/ceph-cm-ansible/pull/544#issuecomment-599076564
  - name: Clean DNF cache
    shell: "dnf clean all && rm -rf /var/cache/dnf/*"
    when:
      - ansible_os_family == "RedHat"
      - ansible_distribution_major_version|int >= 8

  - set_fact:
      ntp_service: ntp
    when: ansible_os_family == "Debian"

  - set_fact:
      ntp_service: ntpd
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int <= 7

  - set_fact:
      ntp_service: chronyd
    when: (ansible_os_family == "RedHat" and ansible_distribution_major_version|int >= 8) or
          ansible_os_family == "Suse"

  - name: "Stop {{ ntp_service }} service"
    service:
      name: "{{ ntp_service }}"
      state: stopped
    when: '"ntp" in ntp_service'

  # The theory here is although we do have the ntp service running on boot,
  # if the time is off, it slowly drifts back in sync.  Since our testnodes
  # are ephemeral, they don't ever have enough time to correctly drift
  # back to the correct time.  So we'll force it in the captured OS images.
  - name: Install ntpdate command if missing
    package:
      name: ntpdate
      state: present
    when: '"ntp" in ntp_service'

  - name: Force time synchronization using stepping | ntp
    command: "ntpdate -b {{ ntp_servers|join(' ') }}"
    when: '"ntp" in ntp_service'

  - name: "Start {{ ntp_service }}"
    service:
      name: "{{ ntp_service }}"
      state: started

  # chronyd needs to be started in order to force time sync. This differs from ntpd.
  - name: Force time synchronization using stepping | chrony
    command: chronyc -a makestep
    when: '"chrony" in ntp_service'

  - name: Sync the hardware clock
    command: "hwclock --systohc"

  - name: Disable cloud init and disruptive apt services
    ansible.builtin.systemd:
      name: "{{ item }}"
      enabled: false
      state: stopped
      masked: true
    loop:
      - cloud-init-local.service
      - cloud-init.service
      - cloud-config.service
      - cloud-final.service
      - unattended-upgrades.service
      - apt-daily.service
      - apt-daily-upgrade.service
      - apt-daily.timer
      - apt-daily-upgrade.timer
    failed_when: false
    when: ansible_os_family == "Debian"

  - name: Disable cloud init networking config
    ansible.builtin.copy:
      dest: /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg
      owner: root
      group: root
      mode: "0644"
      content: |
        network:
          config: disabled
    failed_when: false

  - name: Disable cloud init completely
    ansible.builtin.file:
      path: /etc/cloud/cloud-init.disabled
      state: touch
      owner: root
      group: root
      mode: "0644"

  - name: Remove cloud init state
    ansible.builtin.file:
      path: /var/lib/cloud
      state: absent
    failed_when: false

  - name: Remove cloud init netplan file
    ansible.builtin.file:
      path: /etc/netplan/50-cloud-init.yaml
      state: absent
    failed_when: false
    when: ansible_os_family == "Debian"

  - name: Debian netplan from link config
    block:
      - name: Install netplan link selection script
        ansible.builtin.copy:
          dest: /usr/local/sbin/netplan-from-link.sh
          owner: root
          group: root
          mode: "0755"
          content: |
            #!/usr/bin/env bash
            set -euo pipefail

            OUT="/etc/netplan/01-fog.yaml"
            STAMP="/.cephlab_net_configured"

            if [[ -f "$STAMP" ]]; then
              exit 0
            fi

            rm -f /etc/netplan/*.yaml || true

            pick_iface() {
              for c in /sys/class/net/*/carrier; do
                iface="$(basename "$(dirname "$c")")"

                case "$iface" in
                  lo|docker*|veth*|virbr*|br*|cni*|flannel*|weave*|zt*|wg*|tun*|tap*|sit*|ip6tnl*|gre*|gretap*|erspan*|bond* )
                    continue
                    ;;
                esac

                if [[ -r "$c" ]] && [[ "$(cat "$c")" == "1" ]]; then
                  echo "$iface"
                  return 0
                fi
              done

              ip -4 route show default 2>/dev/null | awk '{for(i=1;i<=NF;i++) if ($i=="dev") {print $(i+1); exit}}' || true
            }

            iface=""
            for _ in $(seq 1 30); do
              iface="$(pick_iface || true)"
              if [[ -n "${iface:-}" ]]; then
                break
              fi
              sleep 1
            done

            if [[ -z "${iface:-}" ]]; then
              echo "netplan-from-link could not find an uplink interface" >&2
              exit 0
            fi

            cat >"$OUT" <<EOF
            network:
              version: 2
              renderer: networkd
              ethernets:
                ${iface}:
                  dhcp4: true
                  dhcp6: false
                  optional: false
                  dhcp4-overrides:
                    use-dns: true
                    use-hostname: true
                  nameservers:
                    addresses: [10.20.192.11]
            EOF

            chmod 0644 "$OUT"

            if command -v netplan >/dev/null 2>&1; then
              netplan generate || true
              netplan apply || true
            fi

            touch "$STAMP"

      - name: Install systemd unit for netplan link selection
        ansible.builtin.copy:
          dest: /etc/systemd/system/netplan-from-link.service
          owner: root
          group: root
          mode: "0644"
          content: |
            [Unit]
            Description=Write netplan from link carrier once
            After=systemd-udev-settle.service local-fs.target
            Wants=systemd-udev-settle.service

            [Service]
            Type=oneshot
            ExecStart=/usr/local/sbin/netplan-from-link.sh
            RemainAfterExit=yes

            [Install]
            WantedBy=multi-user.target

      - name: Enable netplan link selection unit
        ansible.builtin.systemd:
          name: netplan-from-link.service
          enabled: true
          state: started
          daemon_reload: true

      - name: Fog prep disable network manager best effort
        ansible.builtin.systemd:
          name: NetworkManager
          enabled: false
          state: stopped
        failed_when: false

      - name: Fog prep enable networkd
        ansible.builtin.systemd:
          name: systemd-networkd
          enabled: true
          state: started
          daemon_reload: true

      - name: Fog prep avoid wait online hang
        ansible.builtin.systemd:
          name: systemd-networkd-wait-online
          enabled: false
          state: stopped
        failed_when: false

      - name: Fog prep netplan generate
        ansible.builtin.command: netplan generate
        changed_when: false
        failed_when: false

      - name: Fog prep netplan apply
        ansible.builtin.command: netplan apply
        changed_when: true
        failed_when: false
    when: ansible_os_family == "Debian"

  - name: Disable cloud init services
    ansible.builtin.systemd:
      name: "{{ item }}"
      enabled: false
      state: stopped
      masked: true
    loop:
      - cloud-init-local.service
      - cloud-init.service
      - cloud-config.service
      - cloud-final.service
    failed_when: false
    when: ansible_os_family == "RedHat"

  - name: CentOS9 network manager from link config
    block:
      - name: Install network manager link selection script
        ansible.builtin.copy:
          dest: /usr/local/sbin/nm-from-link.sh
          owner: root
          group: root
          mode: "0755"
          content: |
            #!/usr/bin/env bash
            set -euo pipefail

            STAMP="/.cephlab_net_configured"
            if [[ -f "$STAMP" ]]; then
              exit 0
            fi

            pick_iface() {
              for c in /sys/class/net/*/carrier; do
                iface="$(basename "$(dirname "$c")")"

                case "$iface" in
                  lo|docker*|veth*|virbr*|br*|cni*|flannel*|weave*|zt*|wg*|tun*|tap*|sit*|ip6tnl*|gre*|gretap*|erspan*|bond* )
                    continue
                    ;;
                esac

                if [[ -r "$c" ]] && [[ "$(cat "$c")" == "1" ]]; then
                  echo "$iface"
                  return 0
                fi
              done

              ip -4 route show default 2>/dev/null | awk '{for(i=1;i<=NF;i++) if ($i=="dev") {print $(i+1); exit}}' || true
            }

            iface=""
            for _ in $(seq 1 30); do
              iface="$(pick_iface || true)"
              if [[ -n "${iface:-}" ]]; then
                break
              fi
              sleep 1
            done

            if [[ -z "${iface:-}" ]]; then
              echo "nm-from-link could not find an uplink interface" >&2
              exit 0
            fi

            systemctl enable --now NetworkManager || true

            IFACE="$iface"
            CONN="fog-dhcp-${IFACE}"

            # Remove existing connections pinned to this interface (prevents stale MAC/IP settings)
            nmcli -t -f NAME,DEVICE con show | awk -F: -v d="$IFACE" '$2==d {print $1}' | while read -r n; do
              [[ -n "$n" ]] && nmcli con delete "$n" || true
            done

            # Remove same-named conn if present
            nmcli -t -f NAME con show | grep -qx "$CONN" && nmcli con delete "$CONN" || true

            nmcli con add type ethernet ifname "$IFACE" con-name "$CONN" ipv4.method auto ipv6.method ignore
            nmcli con mod "$CONN" connection.autoconnect yes
            nmcli con mod "$CONN" ipv4.ignore-auto-dns yes
            nmcli con mod "$CONN" ipv4.dns "10.20.192.11"
            nmcli con up "$CONN" || true

            touch "$STAMP"

      - name: Install systemd unit for network manager link selection
        ansible.builtin.copy:
          dest: /etc/systemd/system/nm-from-link.service
          owner: root
          group: root
          mode: "0644"
          content: |
            [Unit]
            Description=Write NetworkManager connection from link carrier once
            After=systemd-udev-settle.service local-fs.target
            Wants=systemd-udev-settle.service

            [Service]
            Type=oneshot
            ExecStart=/usr/local/sbin/nm-from-link.sh
            RemainAfterExit=yes

            [Install]
            WantedBy=multi-user.target

      - name: Enable network manager link selection unit
        ansible.builtin.systemd:
          name: nm-from-link.service
          enabled: true
          state: started
          daemon_reload: true

    when:
      - ansible_os_family == "RedHat"
      - ansible_distribution_major_version|int >= 9
