---
- name: Add all machines from inventory to MAAS
  when: inventory_hostname in groups['maas_region_rack_server']
  tags: add_machines
  block:
    - name: Get existing machines in MAAS
      command: "maas {{ maas_admin_username }} machines read"
      register: existing_machines

    - name: Extract existing hostnames
      set_fact:
        existing_hostnames: "{{ existing_machines.stdout | from_json | map(attribute='hostname') | list }}"
    
    - name: Add Machines into MAAS
      vars:
        hostname: "{{ item.split('.')[0] }}"
        mac_address: "{{ hostvars[item]['mac'] }}"
        arch: "{{ hostvars[item]['arch'] }}"
      when: hostname not in existing_hostnames and mac_address is defined and arch is defined
      loop: "{{ groups['testnodes'] }}"
      command: "maas {{ maas_admin_username }} machines create architecture={{ arch }} mac_addresses={{ mac_address }} hostname={{ item }} power_type=manual deployed=true"
      
